PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?collectie ?observatie ?datum ?property ?waarde ?eenheid ?featureOfInterest ?procedure
WHERE {
    ?collectie rdf:type sosa:ObservationCollection ;
        sosa:resultTime ?datum ;
        sosa:madeBySensor ?sensor ;
        sosa:hasMember ?observatie ;
        sosa:hasFeatureOfInterest ?featureOfInterest  .
    ?observatie sosa:observedProperty ?property ;
        sosa:usedProcedure?procedure ;
        sosa:hasResult ?result .
    ?result rdf:value ?waarde .
    OPTIONAL { ?result qudt:hasUnit ?eenheid . }
}



